tap "buo/cask-upgrade"
tap "homebrew/bundle"
tap "homebrew/services"
brew "openssl@3"
brew "autoconf"
brew "python@3.12"
brew "awscli"
brew "bash"
brew "bat"
brew "composer"
brew "coreutils"
brew "dockutil"
brew "tesseract"
brew "ffmpeg"
brew "gh"
brew "gifsicle"
brew "git"
brew "grep"
brew "htop"
brew "httpie"
brew "imagemagick"
brew "jpegoptim"
brew "jq"
brew "mackup"
brew "mas"
brew "mysql", restart_service: true
brew "node"
brew "optipng"
brew "pkg-config"
brew "pngquant"
brew "pure"
brew "python-setuptools"
brew "starship"
brew "subversion"
brew "svgo"
brew "webkit2png"
brew "wget"
brew "yarn"
brew "zsh"
cask "appcleaner"
cask "batteries"
cask "chatgpt"
cask "font-jetbrains-mono"
cask "github"
cask "google-chrome"
cask "herd"
cask "hyper"
cask "imageoptim"
cask "jetbrains-toolbox"
cask "microsoft-auto-update"
cask "microsoft-office"
cask "microsoft-teams"
cask "postman"
cask "qlmarkdown"
cask "quicklook-json"
cask "raycast"
cask "ssh-config-editor"
cask "the-unarchiver"
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Sequel Ace", id: 1518036000
mas "Telegram", id: 747648890
